// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: pkg/pb_gen/Person.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PersonManagementClient is the client API for PersonManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersonManagementClient interface {
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
}

type personManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonManagementClient(cc grpc.ClientConnInterface) PersonManagementClient {
	return &personManagementClient{cc}
}

func (c *personManagementClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := c.cc.Invoke(ctx, "/pb.PersonManagement/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonManagementServer is the server API for PersonManagement service.
// All implementations must embed UnimplementedPersonManagementServer
// for forward compatibility
type PersonManagementServer interface {
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
	mustEmbedUnimplementedPersonManagementServer()
}

// UnimplementedPersonManagementServer must be embedded to have forward compatible implementations.
type UnimplementedPersonManagementServer struct {
}

func (UnimplementedPersonManagementServer) GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}
func (UnimplementedPersonManagementServer) mustEmbedUnimplementedPersonManagementServer() {}

// UnsafePersonManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersonManagementServer will
// result in compilation errors.
type UnsafePersonManagementServer interface {
	mustEmbedUnimplementedPersonManagementServer()
}

func RegisterPersonManagementServer(s grpc.ServiceRegistrar, srv PersonManagementServer) {
	s.RegisterService(&PersonManagement_ServiceDesc, srv)
}

func _PersonManagement_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonManagementServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PersonManagement/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonManagementServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersonManagement_ServiceDesc is the grpc.ServiceDesc for PersonManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersonManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PersonManagement",
	HandlerType: (*PersonManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _PersonManagement_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb_gen/Person.proto",
}
